USE [C:\DOCUMENTS AND SETTINGS\FABRICE\APPLICATION DATA\LINQPAD\SAMPLES\LINQ IN ACTION\NORTHWND.MDF]

SELECT *
FROM [Order Details]
SELECT *
FROM Orders
SELECT *
FROM [Orders Qry]


ALTER TABLE [Order Details]
  ADD FOREIGN KEY (OrderID) REFERENCES Orders (OrderID)

CREATE TABLE A (
  D int FOREIGN KEY REFERENCES E(F),
  B int,
  C int
  CONSTRAINT PK_A_B_C PRIMARY KEY (B,C)
)