USE [C:\DOCUMENTS AND SETTINGS\FABRICE\APPLICATION DATA\LINQPAD\SAMPLES\LINQ IN ACTION\NORTHWND.MDF]
SELECT * FROM Orders
SELECT * FROM Orders WHERE OrderDate ='1996-07-04 00:00:00.000'
SELECT GETDATE(), DATEADD(DAY,365,GETDATE())
SELECT GETDATE(), DATEADD(MONTH,3,GETDATE())
SELECT GETDATE(), DATEADD(YEAR,3,GETDATE())

SELECT DATEDIFF(DAY,GETDATE(),'2018-12-31')
SELECT DATEDIFF(MONTH,GETDATE(),'2018-12-31')
SELECT DATEDIFF(YEAR,GETDATE(),'2018-12-31')

SELECT DATEPART(DAY,GETDATE())

SELECT GETUTCDATE()
